<?php
/**
 * Created by PhpStorm.
 * User: mo
 * Date: 17-8-28
 * Time: 上午10:17
 */

namespace app\demo\tests;


use app\demo\service\UserService;
use herosphp\core\Loader;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{

    private $service;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this -> service = Loader::service(UserService::class);
    }

    /**
     * @test
     *
     */
    public function testIsUser(){
        $this->service->one();
    }

}